### ISSUE TITLE
Where is your code?

### ISSUE THREAD

**Issue by RUAN0007** [hyperchain/hyperchain#52]
May I know where is your code and running script?
I wanna have a try!

**Comment by kewellcjj** [comment]
I'm also looking for codes. As stated in the roadmap, v1.4 should be available in a "public community" last December. However, there are no updates in this repository since early January. Is this project abandoned? Looking forward to hyerchain's response. Thanks!

**Comment by WHUTzju** [comment]
is abandoned?

**Comment by CodingCattwo** [comment]
I wanna build a alliance chain on my own, and this project is great to study on!
If the code will be available, it'll be great, and the docs help me a lot.
